#!/bin/bash

declare -a testcases=("N\nc c a a a b a b\nA\na a a a b b\nN\na a b c\nB\nQ" "n\nx a b b a a a b b b c b a x a a b\na\nc c c b b Q a\nn\nb b b b\nq")
#declare -a testcases=("A\na a a a b b\nQ")
#declare -a testcases=("a\nc c a a a b a b\nq" "n\nc c a a a b a b\nq" "B Q")
echo -ne "Compiling Assignment3.java ....\n"


if javac Assignment3.java; then
	echo -ne "Compile successful\n"
	echo -ne "-----------------------------\n"

	for i in "${testcases[@]}"
	do
		echo -ne "\nRunning test case\t$i:\n"
		echo -ne "----------------------------\n"
		echo -ne $i | java Assignment3
	done
		

else
	echo -ne "\nCompile failed!\n"
fi

